/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappOficialRouteImport } from './routes/_authenticated.whatsapp-oficial'
import { Route as AuthenticatedResponsaveisRouteImport } from './routes/_authenticated.responsaveis'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated.leads'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated.ia'
import { Route as AuthenticatedGestao360RouteImport } from './routes/_authenticated.gestao-360'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated.conversas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedBaseConhecimentoRouteImport } from './routes/_authenticated.base-conhecimento'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated.atendimentos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappOficialRoute =
  AuthenticatedWhatsappOficialRouteImport.update({
    id: '/whatsapp-oficial',
    path: '/whatsapp-oficial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResponsaveisRoute =
  AuthenticatedResponsaveisRouteImport.update({
    id: '/responsaveis',
    path: '/responsaveis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestao360Route = AuthenticatedGestao360RouteImport.update({
  id: '/gestao-360',
  path: '/gestao-360',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBaseConhecimentoRoute =
  AuthenticatedBaseConhecimentoRouteImport.update({
    id: '/base-conhecimento',
    path: '/base-conhecimento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gestao-360': typeof AuthenticatedGestao360Route
  '/ia': typeof AuthenticatedIaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/responsaveis': typeof AuthenticatedResponsaveisRoute
  '/whatsapp-oficial': typeof AuthenticatedWhatsappOficialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gestao-360': typeof AuthenticatedGestao360Route
  '/ia': typeof AuthenticatedIaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/responsaveis': typeof AuthenticatedResponsaveisRoute
  '/whatsapp-oficial': typeof AuthenticatedWhatsappOficialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gestao-360': typeof AuthenticatedGestao360Route
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/responsaveis': typeof AuthenticatedResponsaveisRoute
  '/_authenticated/whatsapp-oficial': typeof AuthenticatedWhatsappOficialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/atendimentos'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/gestao-360'
    | '/ia'
    | '/leads'
    | '/relatorios'
    | '/responsaveis'
    | '/whatsapp-oficial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/atendimentos'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/gestao-360'
    | '/ia'
    | '/leads'
    | '/relatorios'
    | '/responsaveis'
    | '/whatsapp-oficial'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/landing'
    | '/login'
    | '/_authenticated/atendimentos'
    | '/_authenticated/base-conhecimento'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/gestao-360'
    | '/_authenticated/ia'
    | '/_authenticated/leads'
    | '/_authenticated/relatorios'
    | '/_authenticated/responsaveis'
    | '/_authenticated/whatsapp-oficial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp-oficial': {
      id: '/_authenticated/whatsapp-oficial'
      path: '/whatsapp-oficial'
      fullPath: '/whatsapp-oficial'
      preLoaderRoute: typeof AuthenticatedWhatsappOficialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/responsaveis': {
      id: '/_authenticated/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof AuthenticatedResponsaveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-360': {
      id: '/_authenticated/gestao-360'
      path: '/gestao-360'
      fullPath: '/gestao-360'
      preLoaderRoute: typeof AuthenticatedGestao360RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/base-conhecimento': {
      id: '/_authenticated/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedBaseConhecimentoRoute: typeof AuthenticatedBaseConhecimentoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGestao360Route: typeof AuthenticatedGestao360Route
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedResponsaveisRoute: typeof AuthenticatedResponsaveisRoute
  AuthenticatedWhatsappOficialRoute: typeof AuthenticatedWhatsappOficialRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedBaseConhecimentoRoute: AuthenticatedBaseConhecimentoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGestao360Route: AuthenticatedGestao360Route,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedResponsaveisRoute: AuthenticatedResponsaveisRoute,
  AuthenticatedWhatsappOficialRoute: AuthenticatedWhatsappOficialRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
