/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappOficialRouteImport } from './routes/whatsapp-oficial'
import { Route as ResponsaveisRouteImport } from './routes/responsaveis'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IaRouteImport } from './routes/ia'
import { Route as Gestao360RouteImport } from './routes/gestao-360'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappOficialRoute = WhatsappOficialRouteImport.update({
  id: '/whatsapp-oficial',
  path: '/whatsapp-oficial',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsaveisRoute = ResponsaveisRouteImport.update({
  id: '/responsaveis',
  path: '/responsaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const Gestao360Route = Gestao360RouteImport.update({
  id: '/gestao-360',
  path: '/gestao-360',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/gestao-360': typeof Gestao360Route
  '/ia': typeof IaRoute
  '/landing': typeof LandingRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/whatsapp-oficial': typeof WhatsappOficialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/gestao-360': typeof Gestao360Route
  '/ia': typeof IaRoute
  '/landing': typeof LandingRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/whatsapp-oficial': typeof WhatsappOficialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/gestao-360': typeof Gestao360Route
  '/ia': typeof IaRoute
  '/landing': typeof LandingRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/whatsapp-oficial': typeof WhatsappOficialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimentos'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/gestao-360'
    | '/ia'
    | '/landing'
    | '/leads'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/responsaveis'
    | '/whatsapp-oficial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimentos'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/gestao-360'
    | '/ia'
    | '/landing'
    | '/leads'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/responsaveis'
    | '/whatsapp-oficial'
  id:
    | '__root__'
    | '/'
    | '/atendimentos'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/gestao-360'
    | '/ia'
    | '/landing'
    | '/leads'
    | '/login'
    | '/produtos'
    | '/relatorios'
    | '/responsaveis'
    | '/whatsapp-oficial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentosRoute: typeof AtendimentosRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConversasRoute: typeof ConversasRoute
  DashboardRoute: typeof DashboardRoute
  Gestao360Route: typeof Gestao360Route
  IaRoute: typeof IaRoute
  LandingRoute: typeof LandingRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResponsaveisRoute: typeof ResponsaveisRoute
  WhatsappOficialRoute: typeof WhatsappOficialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-oficial': {
      id: '/whatsapp-oficial'
      path: '/whatsapp-oficial'
      fullPath: '/whatsapp-oficial'
      preLoaderRoute: typeof WhatsappOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsaveis': {
      id: '/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof ResponsaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-360': {
      id: '/gestao-360'
      path: '/gestao-360'
      fullPath: '/gestao-360'
      preLoaderRoute: typeof Gestao360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentosRoute: AtendimentosRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConversasRoute: ConversasRoute,
  DashboardRoute: DashboardRoute,
  Gestao360Route: Gestao360Route,
  IaRoute: IaRoute,
  LandingRoute: LandingRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResponsaveisRoute: ResponsaveisRoute,
  WhatsappOficialRoute: WhatsappOficialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
